server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/netdisc?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      # Single file max size
      max-file-size: 50MB
      # All files max size
      max-request-size: 50MB
#mybatis:
#  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.example.demo: debug

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

